#!/usr/bin/env bash
# Install nginx web server
# settup front page
sudo apt-get -y update
sudo apt-get -y Install nginx
sudo service nginx start
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
