#!/usr/bin/env bash
# Install nginx web server
# settup front page
sudo apt-get update -y
sudo apt-get Install nginx -y
sudo apt-get upgrade -y
sudo service nginx start
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
