#!/usr/bin/env bash
# Install and setup nginx server

apt-get update -y && \
apt-get install -y nginx
if [ $? -eq 0 ]
then
service nginx start
echo -e \
"http {
root /var/www/domo;
server {
listen 80;
server_name mrdomo.tech;
rewrite ^/redirect_me/? \
https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
location / {
index index.html;
}
}
}
events {
}" > /etc/nginx/nginx.conf
mkdir -p /var/www/domo
echo "Holberton School" > \
/var/www/domo/index.html
service nginx restart
else
    echo "Could not install nginx"
    exit 1
fi
exit 0
