#!/usr/bin/env bash
# Install and setup nginx server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start

replace="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "29i $replace" /etc/nginx/sites-available/default

sudo service nginx restart
sudo service nginx reload
