#!/usr/bin/env bash
# Install and setup nginx server

replace="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo apt-get update -y && \
sudo apt-get install -y nginx

sudo service nginx start
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i "27i $replace" /etc/nginx/sites-available/default

sudo service nginx restart
sudo service nginx reload
