#!/usr/bin/env bash
# Creates a custom  header
sudo apt-get update -y
sudo apt-get install nginx -y
sudo service nginx start
sudo chmod 777 /usr/share/nginx/html/index.html
echo "Holberton School" > /usr/share/nginx/html/index.html
sudo sed -i "37i\ \tlocation /redirect_me {\n\treturn 301;\n\t}\n" /etc/nginx/sites-enabled/default
sudo touch /usr/share/nginx/html/404.html
sudo chmod 777 /usr/share/nginx/html/404.html
echo -e "Ceci n'est pas une page\n" > /usr/share/nginx/404.html
change="#error_page 404"
new="error_page 404"
sudo sed -i "s/$change/$new/" /etc/nginx/sites-enabled/default
sudo sed -i "27i\ \tadd_header X-Served-By $HOSTNAME;\n" /etc/nginx/sites-enabled/default
sudo service nginx restart
