#!/usr/bin/env bash
# script to change nameservers
cp /etc/hosts ~/temporaryserver
sed -i s/127.0.0.1/127.0.0.2/ ~/temporaryserver
echo "8.8.8.8 facebook.com" >> ~/temporaryserver
cp -f ~/temporaryserver /etc/hosts
